api: 
  url: https://apptwo.contrastsecurity.com/Contrast
  api_key: qE1Ir8pj58rQ077tZD69D1FHgEni7MDh
  service_key: 3HKBV0GAAIJ1ICFO
  user_name: agent_752f0412-dcaf-4e29-9e33-506177bba176@PatricksOrg
agent: 
  service: 
    enable: true
    logger: 
      path: contrast_service.log
      level: ERROR
    host: 127.0.0.1
    port: 30555
